### ISSUE TITLE
AttributeError: 'module' object has no attribute 'rand'

### ISSUE THREAD

**Issue by Sakorah** [chrismarget/certbot-asa#4]
Hi,

I run into some troubles with the plugin. Seems that pyOpenSSL changed some things...

See here: https://github.com/certbot/certbot/issues/5111

Here are the errors I get:
```
2017-11-02 15:07:01,083:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/certbot-0.19.0-py2.7.egg/certbot/client.py", line 452, in deploy_certificate
    fullchain_path=fullchain_path)
  File "build/bdist.linux-x86_64/egg/certbot_asa/configurator.py", line 280, in deploy_cert
    passphrase = base64.encodestring(OpenSSL.rand.bytes(12)).rstrip()
AttributeError: 'module' object has no attribute 'rand'

2017-11-02 15:07:01,083:DEBUG:certbot.error_handler:Calling registered functions
2017-11-02 15:07:01,084:DEBUG:certbot.reporter:Reporting to user: Unable to install the certificate
2017-11-02 15:07:01,084:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/local/lib/python2.7/dist-packages/certbot-0.19.0-py2.7.egg/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python2.7/dist-packages/certbot-0.19.0-py2.7.egg/certbot/main.py", line 705, in run
    _install_cert(config, le_client, domains, new_lineage)
  File "/usr/local/lib/python2.7/dist-packages/certbot-0.19.0-py2.7.egg/certbot/main.py", line 565, in _install_cert
    path_provider.cert_path, path_provider.chain_path, path_provider.fullchain_path)
  File "/usr/local/lib/python2.7/dist-packages/certbot-0.19.0-py2.7.egg/certbot/client.py", line 452, in deploy_certificate
    fullchain_path=fullchain_path)
  File "build/bdist.linux-x86_64/egg/certbot_asa/configurator.py", line 280, in deploy_cert
    passphrase = base64.encodestring(OpenSSL.rand.bytes(12)).rstrip()
AttributeError: 'module' object has no attribute 'rand'
```

**Comment by rsaeks** [comment]
Seeing the same issue as well with a fresh install.
